version: '3'

volumes:
  postgres_data_noveo:

services:
  db:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: qwerty123
      PGDATA: /data/postgres
    ports:
      - "5432"
    volumes:
      - postgres_data_noveo:/data/postgres

  back:
    build: .
    container_name: noveo_back
    command: ./start.sh
    env_file: .env
    environment:
      DEBUG: 'true'
    volumes:
      - .:/noveo_back
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build: .
    container_name: noveo_front
    command: npm run serve
    volumes:
      - .:/noveo_front
    ports:
      - "8080:8080"