# Generated by Django 2.2 on 2019-08-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190808_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(null=True, to='users.Group'),
        ),
    ]
